### ISSUE TITLE
Invalid CloudFormation Template on initial deploy

### ISSUE THREAD

**Issue by oleschaper** [HyperBrain/serverless-aws-alias#66]
I just tried to deploy my project with the plugin enabled but it fails with this error message:

`Serverless: Packaging service...
Serverless: Preparing alias ...
Serverless: Uploading CloudFormation file to S3...
Serverless: Uploading artifacts...
Serverless: Uploading CloudFormation alias file to S3...
Serverless: Validating template...

  Error --------------------------------------------------

  The CloudFormation template is invalid: Template format error: Unresolved resource dependencies [ApiGatewayDeployment1499436937655] in the Resources block of the template

     For debugging logs, run again after setting the "SLS_DEBUG=*" environment variable.

  Stack Trace --------------------------------------------

Error: The CloudFormation template is invalid: Template format error: Unresolved resource dependencies [ApiGatewayDeployment1499436937655] in the Resources block of the template
    at provider.request.catch (/usr/local/lib/node_modules/serverless/lib/plugins/aws/deploy/lib/validateTemplate.js:25:13)
From previous event:
    at AwsDeploy.validateTemplate (/usr/local/lib/node_modules/serverless/lib/plugins/aws/deploy/lib/validateTemplate.js:20:12)
From previous event:
    at Object.aws:deploy:deploy:validateTemplate [as hook] (/usr/local/lib/node_modules/serverless/lib/plugins/aws/deploy/index.js:102:10)
    at BbPromise.reduce (/usr/local/lib/node_modules/serverless/lib/classes/PluginManager.js:233:55)
From previous event:
    at PluginManager.invoke (/usr/local/lib/node_modules/serverless/lib/classes/PluginManager.js:233:22)
    at PluginManager.spawn (/usr/local/lib/node_modules/serverless/lib/classes/PluginManager.js:245:17)
    at AwsDeploy.BbPromise.bind.then (/usr/local/lib/node_modules/serverless/lib/plugins/aws/deploy/index.js:88:48)
From previous event:
    at Object.deploy:deploy [as hook] (/usr/local/lib/node_modules/serverless/lib/plugins/aws/deploy/index.js:84:10)
    at BbPromise.reduce (/usr/local/lib/node_modules/serverless/lib/classes/PluginManager.js:233:55)
From previous event:
    at PluginManager.invoke (/usr/local/lib/node_modules/serverless/lib/classes/PluginManager.js:233:22)
    at PluginManager.run (/usr/local/lib/node_modules/serverless/lib/classes/PluginManager.js:252:17)
    at variables.populateService.then (/usr/local/lib/node_modules/serverless/lib/Serverless.js:104:33)
    at runCallback (timers.js:800:20)
    at tryOnImmediate (timers.js:762:5)
    at processImmediate [as _immediateCallback] (timers.js:733:5)
From previous event:
    at Serverless.run (/usr/local/lib/node_modules/serverless/lib/Serverless.js:91:74)
    at serverless.init.then (/usr/local/lib/node_modules/serverless/bin/serverless:23:50)
    at <anonymous>

  Get Support --------------------------------------------
     Docs:          docs.serverless.com
     Bugs:          github.com/serverless/serverless/issues
     Forums:        forum.serverless.com
     Chat:          gitter.im/serverless/serverless

  Your Environment Information -----------------------------
     OS:                     darwin
     Node Version:           8.1.2
     Serverless Version:     1.14.0`

**Comment by oleschaper** [comment]
I don't know which template I could take a look into, I guess it is generated?
If I disable the plugin it works again.

Thank you for your help!

**Comment by HyperBrain** [comment]
Can you give me more information about your service configuration? The alias plugin moves the APIG deployment to a separate stack (the alias stack). Can you check if there is a reference to the APIG deployment in the `cloudformation-template-update-stack.json` (located in S3)?

This might be missing support for a specific feature of Serverless you use.

Maybe you can post your serverless.yml here, so that I can try to reproduce and fix the issue.

**Comment by HyperBrain** [comment]
Additionally you can use the `--verbose` switch, which will enable more detailed output, also for the alias plugin.

**Comment by oleschaper** [comment]
Hi,

your instincts are right, I am using api keys.
I removed them but now I get another error:

Serverless: Stack update finished...
Serverless: Updating alias stack...

  Serverless Error ---------------------------------------

  [/Resources/UserGetLambdaPermissionApiGateway/DependsOn/0] 'null' values are not allowed in templates

  Stack Trace --------------------------------------------

ServerlessError: [/Resources/UserGetLambdaPermissionApiGateway/DependsOn/0] 'null' values are not allowed in templates
    at Response.req.send (/usr/local/lib/node_modules/serverless/lib/plugins/aws/provider/awsProvider.js:163:20)
    at Request.<anonymous> (/usr/local/lib/node_modules/serverless/node_modules/aws-sdk/lib/request.js:360:18)
    at Request.callListeners (/usr/local/lib/node_modules/serverless/node_modules/aws-sdk/lib/sequential_executor.js:105:20)
    at Request.emit (/usr/local/lib/node_modules/serverless/node_modules/aws-sdk/lib/sequential_executor.js:77:10)
    at Request.emit (/usr/local/lib/node_modules/serverless/node_modules/aws-sdk/lib/request.js:678:14)
    at Request.transition (/usr/local/lib/node_modules/serverless/node_modules/aws-sdk/lib/request.js:22:10)
    at AcceptorStateMachine.runTo (/usr/local/lib/node_modules/serverless/node_modules/aws-sdk/lib/state_machine.js:14:12)
    at /usr/local/lib/node_modules/serverless/node_modules/aws-sdk/lib/state_machine.js:26:10
    at Request.<anonymous> (/usr/local/lib/node_modules/serverless/node_modules/aws-sdk/lib/request.js:38:9)
    at Request.<anonymous> (/usr/local/lib/node_modules/serverless/node_modules/aws-sdk/lib/request.js:680:12)
    at Request.callListeners (/usr/local/lib/node_modules/serverless/node_modules/aws-sdk/lib/sequential_executor.js:115:18)
    at Request.emit (/usr/local/lib/node_modules/serverless/node_modules/aws-sdk/lib/sequential_executor.js:77:10)
    at Request.emit (/usr/local/lib/node_modules/serverless/node_modules/aws-sdk/lib/request.js:678:14)
    at Request.transition (/usr/local/lib/node_modules/serverless/node_modules/aws-sdk/lib/request.js:22:10)
    at AcceptorStateMachine.runTo (/usr/local/lib/node_modules/serverless/node_modules/aws-sdk/lib/state_machine.js:14:12)
    at /usr/local/lib/node_modules/serverless/node_modules/aws-sdk/lib/state_machine.js:26:10
    at Request.<anonymous> (/usr/local/lib/node_modules/serverless/node_modules/aws-sdk/lib/request.js:38:9)
    at Request.<anonymous> (/usr/local/lib/node_modules/serverless/node_modules/aws-sdk/lib/request.js:680:12)
    at Request.callListeners (/usr/local/lib/node_modules/serverless/node_modules/aws-sdk/lib/sequential_executor.js:115:18)
    at callNextListener (/usr/local/lib/node_modules/serverless/node_modules/aws-sdk/lib/sequential_executor.js:95:12)
    at Request.RESET_RETRY_STATE (/usr/local/lib/node_modules/serverless/node_modules/aws-sdk/lib/event_listeners.js:426:9)
    at Request.callListeners (/usr/local/lib/node_modules/serverless/node_modules/aws-sdk/lib/sequential_executor.js:101:18)
    at Request.emit (/usr/local/lib/node_modules/serverless/node_modules/aws-sdk/lib/sequential_executor.js:77:10)
    at Request.emit (/usr/local/lib/node_modules/serverless/node_modules/aws-sdk/lib/request.js:678:14)
    at Request.transition (/usr/local/lib/node_modules/serverless/node_modules/aws-sdk/lib/request.js:22:10)
    at AcceptorStateMachine.runTo (/usr/local/lib/node_modules/serverless/node_modules/aws-sdk/lib/state_machine.js:14:12)
    at /usr/local/lib/node_modules/serverless/node_modules/aws-sdk/lib/state_machine.js:26:10
    at Request.<anonymous> (/usr/local/lib/node_modules/serverless/node_modules/aws-sdk/lib/request.js:38:9)
    at Request.<anonymous> (/usr/local/lib/node_modules/serverless/node_modules/aws-sdk/lib/request.js:680:12)
    at Request.callListeners (/usr/local/lib/node_modules/serverless/node_modules/aws-sdk/lib/sequential_executor.js:115:18)
    at Request.emit (/usr/local/lib/node_modules/serverless/node_modules/aws-sdk/lib/sequential_executor.js:77:10)
    at Request.emit (/usr/local/lib/node_modules/serverless/node_modules/aws-sdk/lib/request.js:678:14)
    at Request.transition (/usr/local/lib/node_modules/serverless/node_modules/aws-sdk/lib/request.js:22:10)
    at AcceptorStateMachine.runTo (/usr/local/lib/node_modules/serverless/node_modules/aws-sdk/lib/state_machine.js:14:12)
    at /usr/local/lib/node_modules/serverless/node_modules/aws-sdk/lib/state_machine.js:26:10
    at Request.<anonymous> (/usr/local/lib/node_modules/serverless/node_modules/aws-sdk/lib/request.js:38:9)
    at Request.<anonymous> (/usr/local/lib/node_modules/serverless/node_modules/aws-sdk/lib/request.js:680:12)
    at Request.callListeners (/usr/local/lib/node_modules/serverless/node_modules/aws-sdk/lib/sequential_executor.js:115:18)
    at Request.emit (/usr/local/lib/node_modules/serverless/node_modules/aws-sdk/lib/sequential_executor.js:77:10)
    at Request.emit (/usr/local/lib/node_modules/serverless/node_modules/aws-sdk/lib/request.js:678:14)
    at Request.transition (/usr/local/lib/node_modules/serverless/node_modules/aws-sdk/lib/request.js:22:10)
    at AcceptorStateMachine.runTo (/usr/local/lib/node_modules/serverless/node_modules/aws-sdk/lib/state_machine.js:14:12)
    at /usr/local/lib/node_modules/serverless/node_modules/aws-sdk/lib/state_machine.js:26:10
    at Request.<anonymous> (/usr/local/lib/node_modules/serverless/node_modules/aws-sdk/lib/request.js:38:9)
    at Request.<anonymous> (/usr/local/lib/node_modules/serverless/node_modules/aws-sdk/lib/request.js:680:12)
    at Request.callListeners (/usr/local/lib/node_modules/serverless/node_modules/aws-sdk/lib/sequential_executor.js:115:18)
    at Request.emit (/usr/local/lib/node_modules/serverless/node_modules/aws-sdk/lib/sequential_executor.js:77:10)
    at Request.emit (/usr/local/lib/node_modules/serverless/node_modules/aws-sdk/lib/request.js:678:14)
    at Request.transition (/usr/local/lib/node_modules/serverless/node_modules/aws-sdk/lib/request.js:22:10)
    at AcceptorStateMachine.runTo (/usr/local/lib/node_modules/serverless/node_modules/aws-sdk/lib/state_machine.js:14:12)
    at /usr/local/lib/node_modules/serverless/node_modules/aws-sdk/lib/state_machine.js:26:10
    at Request.<anonymous> (/usr/local/lib/node_modules/serverless/node_modules/aws-sdk/lib/request.js:38:9)
    at Request.<anonymous> (/usr/local/lib/node_modules/serverless/node_modules/aws-sdk/lib/request.js:680:12)
    at Request.callListeners (/usr/local/lib/node_modules/serverless/node_modules/aws-sdk/lib/sequential_executor.js:115:18)
    at callNextListener (/usr/local/lib/node_modules/serverless/node_modules/aws-sdk/lib/sequential_executor.js:95:12)
    at IncomingMessage.onEnd (/usr/local/lib/node_modules/serverless/node_modules/aws-sdk/lib/event_listeners.js:256:13)
    at emitNone (events.js:110:20)
    at IncomingMessage.emit (events.js:207:7)
    at endReadableNT (_stream_readable.js:1047:12)
    at _combinedTickCallback (internal/process/next_tick.js:102:11)
    at process._tickDomainCallback (internal/process/next_tick.js:198:9)
From previous event:
    at persistentRequest (/usr/local/lib/node_modules/serverless/lib/plugins/aws/provider/awsProvider.js:151:14)
    at doCall (/usr/local/lib/node_modules/serverless/lib/plugins/aws/provider/awsProvider.js:130:9)
    at BbPromise (/usr/local/lib/node_modules/serverless/lib/plugins/aws/provider/awsProvider.js:141:14)
From previous event:
    at persistentRequest (/usr/local/lib/node_modules/serverless/lib/plugins/aws/provider/awsProvider.js:128:38)
    at AwsProvider.request (/usr/local/lib/node_modules/serverless/lib/plugins/aws/provider/awsProvider.js:144:12)
    at AwsAlias.updateAlias (/Users/oleschaper/dev/sviper/projects/superspellsaga/superspellsaga_backend/node_modules/serverless-aws-alias/lib/updateAliasStack.js:82:25)
    at runCallback (timers.js:800:20)
    at tryOnImmediate (timers.js:762:5)
    at processImmediate [as _immediateCallback] (timers.js:733:5)

  Get Support --------------------------------------------
     Docs:          docs.serverless.com
     Bugs:          github.com/serverless/serverless/issues
     Forums:        forum.serverless.com
     Chat:          gitter.im/serverless/serverless

  Your Environment Information -----------------------------
     OS:                     darwin
     Node Version:           8.1.2
     Serverless Version:     1.14.0

I checked the file cloudformation-template-update-alias-stack.json for the resource UserGetLambdaPermissionApiGateway and the DependsOn looks like this (also all the others look like this):

      "DependsOn": [
        null,
        null
      ]

If needed I could send you my serverless.yml per mail.

Thank you!

**Comment by HyperBrain** [comment]
That looks indeed strange. The dependency array should never ever contain null values.
Could you do come tests using my example repo (https://github.com/HyperBrain/serverless-aws-alias-example)?. A plain checkout and deploy of one of the branches should work out of the box.

You could try to configure the API within there step by step to the configuration you're actually using. There must be one step where the issue happens.

If that does not help, I'll have a look at your service definition and try to reproduce it.

**Comment by oleschaper** [comment]
Thank you @HyperBrain

I stripped down my serverless.yml but I can not figure out what is wrong.

This is my serverless.yml file:

---

service: MyBackend

provider:
  name: aws
  runtime: java8
  region: us-east-1
  stage: dev

  memorySize: 512
  timeout: 15 # The default is 6

  versionFunctions: false

  iamRoleStatements: # permissions for all of your functions can be set here
    - Effect: Allow
      Action:
        - dynamodb:*
      Resource:
        - arn:aws:dynamodb:us-east-1:*:*

  # you can define service wide environment variables here
  environment:
    STAGE: ${opt:stage, self:provider.stage}

# you can add packaging information here
package:
  artifact: target/MyBackend-${env:API_VERSION, opt:version}.jar

functions:
  userGet:
    handler: com.acme.my.backend.handler.user.UserGetHandler
    events: # All events associated with this function
      - http:
          path: user/get
          method: any

# you can add CloudFormation resource templates here
resources:
  Resources:
    $ref: ./cloudformation-resources.json

plugins:
  - serverless-aws-alias

---

This is the cloudformation-resources.json:

---

{
  "UserPool": {
    "Type": "AWS::Cognito::IdentityPool",
    "Properties": {
      "IdentityPoolName": "My_User_Pool",
      "AllowUnauthenticatedIdentities": true
    }
  },
  "UserTable": {
    "Type": "AWS::DynamoDB::Table",
    "Properties": {
      "TableName": "My_User_${opt:stage, self:provider.stage}",
      "AttributeDefinitions": [
        {
          "AttributeName": "id",
          "AttributeType": "S"
        }
      ],
      "KeySchema": [
        {
          "AttributeName": "id",
          "KeyType": "HASH"
        }
      ],
      "ProvisionedThroughput": {
        "ReadCapacityUnits": 5,
        "WriteCapacityUnits": 5
      }
    }
  }
}

---

This is the generated cloudformation-template-update-alias-stack.json:

---

{
  "AWSTemplateFormatVersion": "2010-09-09",
  "Description": "Alias stack for MyBackend-dev (dev)",
  "Resources": {
    "ServerlessAliasLogGroup": {
      "Type": "AWS::Logs::LogGroup",
      "Properties": {
        "LogGroupName": "/serverless/MyBackend-dev-dev",
        "RetentionInDays": 7
      }
    },
    "ApiGatewayDeployment1499553574096": {
      "Type": "AWS::ApiGateway::Deployment",
      "Properties": {
        "RestApiId": {
          "Fn::ImportValue": "MyBackend-dev-ApiGatewayRestApi"
        }
      },
      "DependsOn": []
    },
    "ApiGatewayStage": {
      "Type": "AWS::ApiGateway::Stage",
      "Properties": {
        "StageName": "dev",
        "DeploymentId": {
          "Ref": "ApiGatewayDeployment1499553574096"
        },
        "RestApiId": {
          "Fn::ImportValue": "MyBackend-dev-ApiGatewayRestApi"
        },
        "Variables": {
          "SERVERLESS_ALIAS": "dev",
          "SERVERLESS_STAGE": "dev"
        },
        "Description": "Alias stage 'dev' for MyBackend"
      },
      "DependsOn": [
        "ApiGatewayDeployment1499553574096"
      ]
    },
    "UserGetLambdaPermissionApiGateway": {
      "Type": "AWS::Lambda::Permission",
      "Properties": {
        "FunctionName": {},
        "Action": "lambda:InvokeFunction",
        "Principal": "apigateway.amazonaws.com",
        "SourceArn": {
          "Fn::Join": [
            "",
            [
              "arn:aws:execute-api:",
              {
                "Ref": "AWS::Region"
              },
              ":",
              {
                "Ref": "AWS::AccountId"
              },
              ":",
              {
                "Fn::ImportValue": "MyBackend-dev-ApiGatewayRestApi"
              },
              "/*/*"
            ]
          ]
        }
      },
      "DependsOn": [
        null,
        null
      ]
    }
  },
  "Outputs": {
    "ServerlessAliasName": {
      "Description": "Alias the stack represents.",
      "Value": "dev"
    },
    "ServerlessAliasLogGroup": {
      "Description": "Log group for alias.",
      "Value": {
        "Ref": "ServerlessAliasLogGroup"
      },
      "Export": {
        "Name": "MyBackend-dev-dev-LogGroup"
      }
    },
    "AliasFlags": {
      "Description": "Alias flags.",
      "Value": "{\"hasRole\":false}"
    },
    "AliasResources": {
      "Description": "Custom resource references",
      "Value": "[\"UserPool\",\"UserTable\"]"
    },
    "AliasOutputs": {
      "Description": "Custom output references",
      "Value": "[]"
    },
    "ServerlessAliasReference": {
      "Description": "Alias stack reference.",
      "Value": {
        "Fn::ImportValue": "MyBackend-dev-ServerlessAliasReference"
      }
    }
  }
}

**Comment by HyperBrain** [comment]
@oleschaper Thank you for the files 👍 . I'll have a look and try to figure out, what exactly is missing in the plugin and if there's some edge case triggered here.

**Comment by HyperBrain** [comment]
It seems the error is located here:
```
    "UserGetLambdaPermissionApiGateway": {
      "Type": "AWS::Lambda::Permission",
      "Properties": {
        "FunctionName": {},
        "Action": "lambda:InvokeFunction",
        "Principal": "apigateway.amazonaws.com",
        "SourceArn": {
          "Fn::Join": [
            "",
            [
              "arn:aws:execute-api:",
              {
                "Ref": "AWS::Region"
              },
              ":",
              {
                "Ref": "AWS::AccountId"
              },
              ":",
              {
                "Fn::ImportValue": "MyBackend-dev-ApiGatewayRestApi"
              },
              "/*/*"
            ]
          ]
        }
      },
      "DependsOn": [
        null,
        null
      ]
    }
```

The permissions object is not created correctly in your case. Additionally to the _null_ dependencies, there is also an issue with the _FunctionName_ property which is set to an empty object here.

Honestly, I did not try the plugin with Java based code, only JavaScript/Node code. Maybe the SLS compile plugin generates something differently for Java packages. I'll try to setup a system where I can reproduce it.

In the mean-time I'll add the _help-wanted_ tag. Maybe someone using Java can comment on the issue.

**Comment by oleschaper** [comment]
Thank you @HyperBrain

**Comment by HyperBrain** [comment]
Sorry that we did not have any feedback here since now 😢 . I'm not sure how many people use Java and the plugin or tried it. Just let's keep it some more time open.

**Comment by killthrush** [comment]
I'm getting the same error on a set of python 3.6 lambdas.  I'm also using Gateway w/ keys.  I'll try digging into this a bit more and see what I can find.

**Comment by HyperBrain** [comment]
Oh. it's the APIKeys. I did not add support for them yet 🤔 . Maybe I should push that and do an update release soon.

**Comment by killthrush** [comment]
That would be awesome - I'd be happy to test it out for you!

**Comment by HyperBrain** [comment]
I'll come back to you as soon as there is anything to test 😄

**Comment by HyperBrain** [comment]
@killthrush Can you provide me with a simple test project that uses API keys? I want to go for an implementation within the next days and it would be better to have something at hand that reflects reality.

**Comment by killthrush** [comment]
@HyperBrain - here you go: https://github.com/killthrush/serverless-sample

I was able to reproduce the reported error using this project.  Thanks!

**Comment by HyperBrain** [comment]
@killthrush Thank you. I'll have some time over the weekend to take care of it and if it works well, also provide an implementation.

**Comment by HyperBrain** [comment]
API Key support is handled with #25 .

**Comment by sambhusai** [comment]
I am also getting the same issue with Java Runtime for Lambda function. I am using the ApiKeys. Removing ApiKeys, it works.

**Comment by HyperBrain** [comment]
Sorry for the very late reply. I was quite overloaded with my work and maintaining the webpack plugin and Serverless. The alias plugin somehow fell off the table ....

I will take care of the remaining issues now, especially API keys, DynamoDB triggers and SNS manual arns.

**Comment by killthrush** [comment]
Thanks!  Still happy to test this out whenever there's something new to look at.

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by sambhusai** [comment]
Thanks @HyperBrain.

**Comment by eshanaka** [comment]
This is what I have noticed, hopefully, it'll be useful to fix the issue.

I have noticed API-key creation and trying to associate with an HTTP endpoint can reproduce the issue. (API Key and usage plan creation and the association was working fine before enabling the aws-alias plugin

How I define the apiKey and usage plan

`
#  apiKeys:
#    - ${opt:stage}-apiKey
#  usagePlan:
#    throttle:
#      burstLimit: 1
#      rateLimit: 1`

Associate with,

```
 - http:
            path: /functionName
            method: get
            private: true
            integration: lambda
```

**Comment by HyperBrain** [comment]
@eshanaka API Keys are still a not implemented feature (see #25 ). It would be great if someone could add support.

**Comment by eshanaka** [comment]
Thanks for the quick response @HyperBrain, I would really like to contribute, let me get familiar with the implementation little bit more and see how it goes.

**Comment by alinefm** [comment]
Any update on this?

I am having the same problem with python3.6 Lambdas and API Gateway but without API Keys.

**Comment by MartinRisk** [comment]
Same problem from .Net lambda's also wihout API Keys

Any update ?
