### ISSUE TITLE
Alias plugin abouts with "Unable to retrieve template" error

### ISSUE THREAD

**Issue by arabold** [HyperBrain/serverless-aws-alias#86]
After patching the Alias stack manually (due to issue #85) I cannot deploy anymore at all :) Now the alias plugin aborts with an error:
```
Error: Unable to retrieve template for my-project-dev-dev: undefined
    at _provider.request.then.catch.err (/Users/arabold/git/my-project/node_modules/serverless-aws-alias/lib/stackInformation.js:71:28)
From previous event:
    at AwsAlias.aliasStackLoadTemplate (/Users/arabold/git/my-project/node_modules/serverless-aws-alias/lib/stackInformation.js:70:9)
    at aliasStackGetAliasStackNames.mapSeries.stack (/Users/arabold/git/my-project/node_modules/serverless-aws-alias/lib/stackInformation.js:82:69)
From previous event:
    at AwsAlias.aliasStackLoadAliasTemplates (/Users/arabold/git/my-project/node_modules/serverless-aws-alias/lib/stackInformation.js:82:4)
From previous event:
    at AwsAlias.aliasStackLoadCurrentCFStackAndDependencies (/Users/arabold/git/my-project/node_modules/serverless-aws-alias/lib/stackInformation.js:147:25)
From previous event:
    at Object.before:aws:deploy:deploy:createStack [as hook] (/Users/arabold/git/my-project/node_modules/serverless-aws-alias/index.js:112:6)
    at BbPromise.reduce (/Users/arabold/git/my-project/node_modules/serverless/lib/classes/PluginManager.js:368:55)
From previous event:
    at PluginManager.invoke (/Users/arabold/git/my-project/node_modules/serverless/lib/classes/PluginManager.js:368:22)
    at PluginManager.spawn (/Users/arabold/git/my-project/node_modules/serverless/lib/classes/PluginManager.js:386:17)
    at AwsDeploy.BbPromise.bind.then (/Users/arabold/git/my-project/node_modules/serverless/lib/plugins/aws/deploy/index.js:101:48)
From previous event:
    at Object.deploy:deploy [as hook] (/Users/arabold/git/my-project/node_modules/serverless/lib/plugins/aws/deploy/index.js:97:10)
    at BbPromise.reduce (/Users/arabold/git/my-project/node_modules/serverless/lib/classes/PluginManager.js:368:55)
From previous event:
    at PluginManager.invoke (/Users/arabold/git/my-project/node_modules/serverless/lib/classes/PluginManager.js:368:22)
    at PluginManager.run (/Users/arabold/git/my-project/node_modules/serverless/lib/classes/PluginManager.js:399:17)
    at variables.populateService.then (/Users/arabold/git/my-project/node_modules/serverless/lib/Serverless.js:102:33)
    at runCallback (timers.js:666:20)
    at tryOnImmediate (timers.js:639:5)
    at processImmediate [as _immediateCallback] (timers.js:611:5)
From previous event:
    at Serverless.run (/Users/arabold/git/my-project/node_modules/serverless/lib/Serverless.js:89:74)
    at serverless.init.then (/Users/arabold/git/my-project/node_modules/serverless/bin/serverless:42:50)
```

I'll spend some time debugging it locally but posted this stack here for reference.

**Comment by arabold** [comment]
Oh, the issue is that the manually patched template now is YAML instead of JSON. That's why the parser fails with an error. Stupid me... I guess this could be some kind of a feature request but then, on the other hand, if you use `sls` the way it is supposed to, you should never run into this scenario in first place.
